### ISSUE TITLE
Extracting cnic data

### ISSUE THREAD

**Issue by hassanrehman01398** [maxpaynestory/Pakistan-NIC-detector-Tensorflow#1]
How can we extract data from cnic?what is the workflow for that?

**Comment by maxpaynestory** [comment]
You could extract data by using an OCR.

**Comment by hassanrehman01398** [comment]
Your card is detecting even white board also. What is the accuracy of your model?

**Comment by maxpaynestory** [comment]
Its accuracy is pretty bad. You could train a new model if you need more accuracy.
